footprint: [[0.21, 0.22], [0.21, -0.22], [-0.21, -0.22], [-0.21, 0.22]]

# http://wiki.ros.org/costmap_2d/hydro/staticmap
static_layer:
  unknown_cost_value: -1
  lethal_cost_threshold: 100
  map_topic: map
  first_map_only: false
  subscribe_to_updates: false
  track_unknown_space: true
  use_maximum: false
  trinary_costmap: true

# http://wiki.ros.org/costmap_2d/hydro/obstacles
obstacle_layer:
  max_obstacle_height: 0.3
  obstacle_range: 2.5
  raytrace_range: 3.0
  track_unknown_space: false
  footprint_clearing_enabled: true
  combination_method: 1
  # assuming receiving a cloud from rtabmap_ros/obstacles_detection node
  observation_sources: point_cloud_sensor


  point_cloud_sensor: 
    sensor_frame: zed2_left_camera_frame
    data_type: PointCloud2
    topic: rtabmap/local_grid_obstacle
    expected_update_rate: 10.0
    marking: true
    clearing: true
    min_obstacle_height: -99999.0
    max_obstacle_height: 99999.0


# http://wiki.ros.org/costmap_2d/hydro/inflation
inflation_layer:
  inflation_radius: 0.4
  cost_scaling_factor: 30.0
